### ISSUE TITLE
74.48% (reproduced) VS 74.76% (claimed) on Clothing1M ?

### ISSUE THREAD

**Issue by Openning07** [LiJunnan1992/DivideMix#1]
First, thank you for sharing your code ~
Do I miss some important details to reproduce the result claimed in the paper? Or there is some fluctuation in the final result and the **74.76%** is the best result in your experiments on Clothing1M dataset ?

**Comment by LiJunnan1992** [comment]
Hi! Thanks for trying the code! I think a 0.3% fluctuation could be normal because of the randomness in network initialization, data sampling, and different machines, etc.

74.76% was the result I got by running the same code with one run only. The models for test was selected from the best validation epochs.  Here is my log output:

Validation Epoch:0      Acc1:69.06  Acc2:67.88
Validation Epoch:1      Acc1:68.41  Acc2:69.23
Validation Epoch:2      Acc1:68.53  Acc2:68.17
Validation Epoch:3      Acc1:70.53  Acc2:69.25
Validation Epoch:4      Acc1:70.70  Acc2:70.46
Validation Epoch:5      Acc1:71.17  Acc2:70.89
Validation Epoch:6      Acc1:71.04  Acc2:70.54
Validation Epoch:7      Acc1:70.30  Acc2:69.97
Validation Epoch:8      Acc1:71.64  Acc2:71.77
Validation Epoch:9      Acc1:71.08  Acc2:71.77
Validation Epoch:10      Acc1:71.67  Acc2:70.78
Validation Epoch:11      Acc1:71.65  Acc2:71.48
Validation Epoch:12      Acc1:72.18  Acc2:71.88
Validation Epoch:13      Acc1:71.17  Acc2:72.34
Validation Epoch:14      Acc1:72.82  Acc2:71.77
Validation Epoch:15      Acc1:71.86  Acc2:72.12
Validation Epoch:16      Acc1:73.00  Acc2:72.14
Validation Epoch:17      Acc1:71.19  Acc2:72.04
Validation Epoch:18      Acc1:72.12  Acc2:72.52
Validation Epoch:19      Acc1:71.98  Acc2:72.08
Validation Epoch:20      Acc1:71.56  Acc2:72.42
Validation Epoch:21      Acc1:72.75  Acc2:72.97
Validation Epoch:22      Acc1:72.41  Acc2:72.19
Validation Epoch:23      Acc1:72.81  Acc2:73.26
Validation Epoch:24      Acc1:72.98  Acc2:71.42
Validation Epoch:25      Acc1:72.14  Acc2:73.31
Validation Epoch:26      Acc1:73.05  Acc2:72.26
Validation Epoch:27      Acc1:72.53  Acc2:73.57
Validation Epoch:28      Acc1:72.97  Acc2:72.69
Validation Epoch:29      Acc1:72.56  Acc2:73.06
Validation Epoch:30      Acc1:71.86  Acc2:72.04
Validation Epoch:31      Acc1:72.20  Acc2:71.28
Validation Epoch:32      Acc1:72.08  Acc2:71.42
Validation Epoch:33      Acc1:72.33  Acc2:73.03
Validation Epoch:34      Acc1:72.17  Acc2:72.58
Validation Epoch:35      Acc1:71.07  Acc2:72.42
Validation Epoch:36      Acc1:71.90  Acc2:72.84
Validation Epoch:37      Acc1:71.88  Acc2:72.39
Validation Epoch:38      Acc1:69.68  Acc2:72.35
Validation Epoch:39      Acc1:72.70  Acc2:72.74
Validation Epoch:40      Acc1:73.21  Acc2:73.62
Validation Epoch:41      Acc1:74.14  Acc2:74.03
Validation Epoch:42      Acc1:74.17  Acc2:74.51
Validation Epoch:43      Acc1:74.09  Acc2:73.66
Validation Epoch:44      Acc1:73.56  Acc2:73.96
Validation Epoch:45      Acc1:74.07  Acc2:74.21
Validation Epoch:46      Acc1:74.32  Acc2:73.74
Validation Epoch:47      Acc1:73.70  Acc2:74.11
Validation Epoch:48      Acc1:73.96  Acc2:74.15
Validation Epoch:49      Acc1:74.31  Acc2:73.29
Validation Epoch:50      Acc1:73.83  Acc2:73.47
Validation Epoch:51      Acc1:73.64  Acc2:73.37
Validation Epoch:52      Acc1:73.98  Acc2:74.13
Validation Epoch:53      Acc1:73.90  Acc2:73.74
Validation Epoch:54      Acc1:73.80  Acc2:74.02
Validation Epoch:55      Acc1:73.55  Acc2:74.03
Validation Epoch:56      Acc1:73.17  Acc2:74.44
Validation Epoch:57      Acc1:74.25  Acc2:73.99
Validation Epoch:58      Acc1:73.58  Acc2:73.94
Validation Epoch:59      Acc1:73.81  Acc2:73.61
Validation Epoch:60      Acc1:74.04  Acc2:74.17
Validation Epoch:61      Acc1:73.36  Acc2:74.26
Validation Epoch:62      Acc1:73.77  Acc2:73.84
Validation Epoch:63      Acc1:73.85  Acc2:73.86
Validation Epoch:64      Acc1:74.00  Acc2:73.76
Validation Epoch:65      Acc1:74.10  Acc2:73.39
Validation Epoch:66      Acc1:73.28  Acc2:73.84
Validation Epoch:67      Acc1:73.95  Acc2:73.74
Validation Epoch:68      Acc1:74.05  Acc2:74.10
Validation Epoch:69      Acc1:74.11  Acc2:73.94
Validation Epoch:70      Acc1:73.96  Acc2:74.11
Validation Epoch:71      Acc1:74.15  Acc2:74.27
Validation Epoch:72      Acc1:73.83  Acc2:73.28
Validation Epoch:73      Acc1:73.62  Acc2:74.09
Validation Epoch:74      Acc1:74.09  Acc2:73.74
Validation Epoch:75      Acc1:73.93  Acc2:73.66
Validation Epoch:76      Acc1:73.93  Acc2:73.88
Validation Epoch:77      Acc1:72.81  Acc2:74.03
Validation Epoch:78      Acc1:73.94  Acc2:73.72
Validation Epoch:79      Acc1:73.18  Acc2:74.43
Validation Epoch:80      Acc1:74.51  Acc2:74.00
Test Accuracy:74.76
